/**
 * Apply Drizzle migrations to the Neon DB pointed at by DATABASE_URL.
 *
 * Run with: `npm run db:migrate`
 *
 * The `migrate()` helper from drizzle-orm/neon-http reads the SQL files
 * in ./drizzle (generated by `npm run db:generate`) and applies any
 * that haven't run yet. Migration history is tracked in a
 * `__drizzle_migrations` table that drizzle manages.
 */

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { migrate } from "drizzle-orm/neon-http/migrator";

// Env loading: scripts are invoked via `node --env-file=.env.local`
// (see package.json scripts). This avoids adding a dotenv dep.

async function main() {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) {
    throw new Error("DATABASE_URL is not set. Aborting migration.");
  }

  const sql = neon(url);
  const db = drizzle(sql);

  console.log("[migrate] applying migrations from ./drizzle …");
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("[migrate] done.");
}

main().catch((err) => {
  console.error("[migrate] failed:", err);
  process.exit(1);
});
